#!/usr/bin/env bash
#A Bash script that configures a new Ubuntu machine nginx

apt-get -y update
apt-get -y install nginx
ufw allow  'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx restart

