#!/usr/bin/env bash
#A Bash script that configures a new Ubuntu machine nginx

apt-get -y update
apt-get -y install nginx
ufw allow  'Nginx HTTP' #nginx should be listed on port 80
echo 'Hello World!'
service nginx restart

