#!/usr/bin/env bash

#The network a computer in local is connected to is?
#The type of network could connect an office in one building to another office in a building a few streets away?
#The network do you use when you browse www.google.com from your smartphone is?

3
3
1
