#!/usr/bin/env bash
#This script loops fro  1-10,
#Displays bd luck fro the 4th loop iteration,
#Displays good luck for the 8th iteration
#Displays Best School for the other iterations.
#Using while loop, if, elif & else statements.

i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]; then
	   echo "bad luck"
	elif [ $i -eq 8 ]; then
	   echo "good luck"
	else
	   echo "Best School"
	fi
	i=$((i+1))
done
